version: "3.8"

services:
  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - nginx_data:/var/log/nginx/
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - lemp

  php:
    build:
      context: "./.docker/php"
    container_name: php
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./.docker/php/php.ini:/usr/local/etc/php.ini
    networks:
      - lemp

  mysql:
    image: mysql:8.0
    container_name: mysql
    depends_on:
      - php
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      # default username = root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database
    volumes:
      - ./.docker/.data/test:/var/lib/mysql
    networks:
      - lemp

  composer:
    image: composer:2.2.4
    container_name: composer
    volumes:
      - ./src/:/app
    networks:
      - lemp

volumes:
  nginx_data: {}

networks:
  lemp:
    driver: bridge
